#!/usr/bin/env python3
"""Generates the dnspython-built messages of the interop corpus.

    python3 tests/corpus/dnspython/gen_messages.py

Writes, with dnspython (time fixed at 1791104299, 2026-10-04T08:58:19Z):

- tsig.txt: for each TSIG algorithm dnspython implements (RFC 8945 §6,
  including the truncated HMAC-SHA-2 variants of RFC 4635 §3.1), a signed
  query and the signed response to it, plus a BADTIME error response and a
  three-message signed zone-transfer stream (RFC 8945 §5.3.1). Columns:
  name, algorithm, key name, base64 secret, then the messages in hex.
- update.txt: dynamic updates (RFC 2136) built with dns.update, one per
  line: description, hex.
- ../dnspython-edns-*.hex: responses carrying every EDNS option dnspython
  builds (RFC 5001, 6975, 7314, 7828, 7830, 7871, 7873, 7901, 8914, 9567),
  in the corpus format, so tests/corpus.rs and tests/dig_display.rs
  exercise them too.

tests/interop_dnspython.rs checks them with dnsbox.
"""

import base64
import os
import sys
import time

import dns.edns
import dns.message
import dns.name
import dns.rcode
import dns.rdatatype
import dns.rrset
import dns.tsig
import dns.update
import dns.version

HERE = os.path.dirname(os.path.abspath(__file__))
CORPUS = os.path.dirname(HERE)
sys.path.insert(0, CORPUS)
sys.dont_write_bytecode = True
import dig_reference  # noqa: E402 (tests/corpus/dig_reference.py)

NOW = 1791104299
time.time = lambda: float(NOW)  # TSIG time signed

SECRET = bytes(range(32))
ALGORITHMS = [
    dns.tsig.HMAC_MD5, dns.tsig.HMAC_SHA1, dns.tsig.HMAC_SHA224, dns.tsig.HMAC_SHA256,
    dns.tsig.HMAC_SHA256_128, dns.tsig.HMAC_SHA384, dns.tsig.HMAC_SHA384_192,
    dns.tsig.HMAC_SHA512, dns.tsig.HMAC_SHA512_256,
]


def keyring(name, alg):
    return {dns.name.from_text(name): dns.tsig.Key(name, base64.b64encode(SECRET).decode(), alg)}


def tsig_lines():
    secret = base64.b64encode(SECRET).decode()
    lines = []
    for alg in ALGORITHMS:
        keyname = f"{alg.to_text().split('.')[0]}.key."
        ring = keyring(keyname, alg)
        q = dns.message.make_query("www.example.com.", "A", id=0x1234, use_edns=0)
        q.use_tsig(ring, keyname, algorithm=alg)
        qw = q.to_wire()
        r = dns.message.make_response(q)
        r.answer.append(dns.rrset.from_text("www.example.com.", 300, "IN", "A", "192.0.2.1"))
        rw = r.to_wire()
        lines.append(f"query\t{alg}\t{keyname}\t{secret}\t{qw.hex()}\t{rw.hex()}")
    # A BADTIME error response: the server's time goes in other data
    # (RFC 8945 §5.2.3).
    alg = dns.tsig.HMAC_SHA256
    keyname = "tsig-key."
    ring = keyring(keyname, alg)
    q = dns.message.make_query("example.com.", "SOA", id=0x4321)
    q.use_tsig(ring, keyname, algorithm=alg)
    qw = q.to_wire()
    r = dns.message.make_response(q)
    r.use_tsig(ring, keyname, algorithm=alg, tsig_error=dns.rcode.BADTIME,
               other_data=(NOW + 1000).to_bytes(6, "big"), original_id=0x4321)
    r.request_mac = q.mac
    rw = r.to_wire()
    lines.append(f"badtime\t{alg}\t{keyname}\t{secret}\t{qw.hex()}\t{rw.hex()}")
    # A signed AXFR stream: every message signed, each MAC chained to the
    # previous one (RFC 8945 §5.3.1).
    q = dns.message.make_query("example.com.", "AXFR", id=0x5678)
    q.use_tsig(ring, keyname, algorithm=alg)
    qw = q.to_wire()
    soa = dns.rrset.from_text("example.com.", 3600, "IN", "SOA",
                              "ns.example.com. hostmaster.example.com. 1 7200 3600 1209600 300")
    parts = [
        [soa, dns.rrset.from_text("example.com.", 3600, "IN", "NS", "ns.example.com.")],
        [dns.rrset.from_text("ns.example.com.", 3600, "IN", "A", "192.0.2.53")],
        [dns.rrset.from_text("www.example.com.", 3600, "IN", "A", "192.0.2.80"), soa],
    ]
    ctx = None
    stream = []
    for i, rrsets in enumerate(parts):
        r = dns.message.make_response(q)
        if i > 0:
            r.question = []
        r.answer.extend(rrsets)
        stream.append(r.to_wire(multi=True, tsig_ctx=ctx).hex())
        ctx = r.tsig_ctx
    lines.append(f"axfr\t{alg}\t{keyname}\t{secret}\t{qw.hex()}\t" + "\t".join(stream))
    header = [
        f"# Generated by gen_messages.py with dnspython {dns.version.version}; secret = 00 01 .. 1f.",
        "# kind<TAB>algorithm<TAB>key name<TAB>base64 secret<TAB>request hex<TAB>response hex...",
    ]
    with open(os.path.join(HERE, "tsig.txt"), "w") as f:
        f.write("\n".join(header + lines) + "\n")


def update_lines():
    out = []

    def add(desc, u):
        out.append(f"{desc}\t{u.to_wire().hex()}")

    u = dns.update.UpdateMessage("example.com.", id=0x1111)
    u.present("www")
    u.present("www", "A")
    u.present("mail", "MX", "10 mx.example.com.")
    u.absent("new")
    u.absent("www", "AAAA")
    u.add("new", 300, "A", "192.0.2.10")
    u.add("new", 300, "TXT", '"created by dnspython"')
    u.replace("www", 600, "A", "192.0.2.80")
    u.delete("old")
    u.delete("www", "AAAA")
    u.delete("mail", "MX", "10 mx.example.com.")
    add("prerequisites and updates", u)
    u = dns.update.UpdateMessage("example.com.", id=0x2222)
    u.add("_sip._udp", 3600, "SRV", "10 60 5060 sip.example.com.")
    u.add("@", 3600, "CAA", '0 issue "ca.example.net"')
    add("additions", u)
    with open(os.path.join(HERE, "update.txt"), "w") as f:
        f.write(f"# Generated by gen_messages.py with dnspython {dns.version.version}:\n")
        f.write("# description<TAB>message hex\n")
        f.write("\n".join(out) + "\n")


def corpus_file(label, msg, what):
    wire = msg.to_wire()
    lines = [
        "# dnsbox interop corpus: a DNS response built with dnspython, unmodified.",
        f"# built by:  tests/corpus/dnspython/gen_messages.py, dnspython {dns.version.version}",
        f"# content:   {what}",
        f"# size:      {len(wire)} bytes",
    ]
    hexed = wire.hex()
    lines += [hexed[i:i + 64] for i in range(0, len(hexed), 64)]
    with open(os.path.join(CORPUS, label + ".hex"), "w") as f:
        f.write("\n".join(lines) + "\n")
    dig_reference.render(label)


def edns_messages():
    q = dns.message.make_query("www.example.com.", "A", id=0x0e05)
    r = dns.message.make_response(q)
    r.answer.append(dns.rrset.from_text("www.example.com.", 300, "IN", "A", "192.0.2.1"))
    r.use_edns(0, dns.flags.DO, 1232, options=[
        dns.edns.NSIDOption(b"dnspython-ns1"),
        dns.edns.ECSOption("192.0.2.0", 24, 16),
        dns.edns.CookieOption(bytes(range(8)), bytes(range(16, 32))),
        dns.edns.EDEOption(dns.edns.EDECode.STALE_ANSWER, "served stale"),
        dns.edns.EDEOption(dns.edns.EDECode.OTHER),
        dns.edns.GenericOption(dns.edns.OptionType.EXPIRE, (604800).to_bytes(4, "big")),
        dns.edns.GenericOption(dns.edns.OptionType.KEEPALIVE, (1200).to_bytes(2, "big")),
        dns.edns.ReportChannelOption(dns.name.from_text("agent.example.net.")),
        dns.edns.GenericOption(dns.edns.OptionType.PADDING, bytes(11)),
    ])
    corpus_file("dnspython-edns-options", r,
                "NSID, ECS 192.0.2.0/24 scope 16, cookie, two EDEs, EXPIRE, "
                "KEEPALIVE, Report-Channel, padding")
    q = dns.message.make_query("www.example.com.", "AAAA", id=0x0e06)
    r = dns.message.make_response(q)
    r.set_rcode(dns.rcode.SERVFAIL)
    r.use_edns(0, 0, 4096, options=[
        dns.edns.ECSOption("2001:db8:1234::", 48, 0),
        dns.edns.EDEOption(dns.edns.EDECode.DNSSEC_BOGUS, "RRSIG A expired"),
        dns.edns.GenericOption(dns.edns.OptionType.DAU, bytes([8, 13, 15])),
        dns.edns.GenericOption(dns.edns.OptionType.DHU, bytes([1, 2, 4])),
        dns.edns.GenericOption(dns.edns.OptionType.N3U, bytes([1])),
        dns.edns.GenericOption(dns.edns.OptionType.CHAIN, b"\x07example\x03com\x00"),
    ])
    corpus_file("dnspython-edns-ecs6-ede", r,
                "SERVFAIL, ECS 2001:db8:1234::/48, EDE 6, DAU, DHU, N3U, CHAIN")


def main():
    tsig_lines()
    update_lines()
    edns_messages()


if __name__ == "__main__":
    main()
