//! SIG(0) interoperability with BIND 9.18 `nsupdate -k`.
//!
//! `tests/data/named/sig0-*.query.bin` are dynamic updates signed by
//! `nsupdate` with throwaway keys generated by `dnssec-keygen -T KEY` for
//! this test (October 2026; their private halves are below). The
//! signatures are checked with `purecrypto` (a dev-dependency only), and
//! the deterministic algorithms (Ed25519, RSA PKCS#1 v1.5) are re-signed
//! through dnsbox to reproduce BIND's messages byte for byte.

use dnsbox::dnssec::Algorithm;
use dnsbox::rdata::{RData, Sig};
use dnsbox::sig0::{self, Sig0Signer, Sig0Verifier, SignedData, Validity};
use dnsbox::{Error, Message, MessageBuilder, Name, NameBuf};
use purecrypto::bignum::BoxedUint;
use purecrypto::ec::ecdsa::{EcdsaPublicKey, Signature as EcdsaSignature};
use purecrypto::ec::{Ed25519PrivateKey, Ed25519PublicKey, Ed25519Signature};
use purecrypto::hash::Sha256;
use purecrypto::rsa::{BoxedRsaPrivateKey, BoxedRsaPublicKey};

fn data(name: &str) -> Vec<u8> {
    let path = format!("{}/tests/data/named/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read(&path).unwrap_or_else(|e| panic!("{path}: {e}"))
}

fn b64(s: &str) -> Vec<u8> {
    const A: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = Vec::new();
    let (mut acc, mut bits) = (0u32, 0);
    for c in s.bytes().filter(|c| !c.is_ascii_whitespace() && *c != b'=') {
        acc = (acc << 6) | A.iter().position(|&a| a == c).unwrap() as u32;
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            out.push((acc >> bits) as u8);
        }
    }
    out
}

/// The test keys (public KEY RDATA key material, from `K*.key`).
const ED25519_PUB: &str = "/JT1WgHpThqMfR1RpDfBV3xLCySTgQSMI0gr3uKsAOg=";
const ED25519_SEED: &str = "wc91WF2mAjwrMWJU1aFsSeiDc54mTL5F1W55Qnpf2sg=";
const P256_PUB: &str = "vRStDPmGR3DGa7ZaY7BYOZj9OnkXlv9M+97TPpOluRzwFx6jQdy6MMID\
                        LNh3wGko1h2oTcJyNAP8Air0+eaXog==";
const RSA_PUB: &str = "AwEAAdGkbUSXMz2MyUucJePf58rl7SwZI4lkzXSjMMVwVLIwNOP/B00y\
                       2/mT/UOXvlFYMpAlVIgIf+TWfZpnyFVa7R9t3XgJeJFE8mrCDGy7YI7W\
                       gMeRYK9CCWZ/kzC2TDa5D/gE2q9GQwwNjBNJfnPtA34DA4o8Vn5KhvSE\
                       QISUx0UH";
const RSA_D: &str = "GR+pcKTmISQ0I3mNGOgGcUxoxfYlShvoe2frOl4h6FDapdA0Yc4MirZvjaAr0LfPJ3Mx\
                     1DOgkB4cY1q4qXICJKBlX5bzchpr6J5DGGrsZPgMixdvDWCXsB+xkBxFFzxtOdvWT1HY\
                     o3kdsUE/knOcffWjftJqbole9hnm/gbqULE=";

/// A verifier for one KEY (name, algorithm, key tag, public key).
struct Key {
    name: NameBuf,
    algorithm: u8,
    tag: u16,
    public: Vec<u8>,
}

impl Key {
    fn new(name: &str, algorithm: u8, tag: u16, public: &str) -> Self {
        Key {
            name: name.parse().unwrap(),
            algorithm,
            tag,
            public: b64(public),
        }
    }

    /// RSA public key from DNSKEY/KEY RDATA (RFC 3110 §2).
    fn rsa(&self) -> (BoxedUint, BoxedUint) {
        let elen = self.public[0] as usize;
        let e = BoxedUint::from_be_bytes(&self.public[1..1 + elen]);
        let n = BoxedUint::from_be_bytes(&self.public[1 + elen..]);
        (n, e)
    }
}

impl Sig0Verifier for Key {
    fn verify(&self, sig: &Sig<'_>, data: &[&[u8]]) -> dnsbox::Result<()> {
        if sig.signer_name != self.name.as_name()
            || sig.algorithm.get() != self.algorithm
            || sig.key_tag != self.tag
        {
            return Err(Error::BadKey);
        }
        let msg = data.concat();
        let ok = match self.algorithm {
            15 => {
                let pk = Ed25519PublicKey::from_bytes(self.public[..].try_into().unwrap());
                let s: [u8; 64] = sig.signature.try_into().map_err(|_| Error::BadSignature)?;
                pk.verify(&msg, &Ed25519Signature::from_bytes(s)).is_ok()
            }
            13 => {
                let mut sec1 = vec![4];
                sec1.extend_from_slice(&self.public);
                let pk = EcdsaPublicKey::from_sec1(&sec1).unwrap();
                let s: [u8; 64] = sig.signature.try_into().map_err(|_| Error::BadSignature)?;
                pk.verify::<Sha256>(&msg, &EcdsaSignature::from_bytes(&s))
                    .is_ok()
            }
            8 => {
                let (n, e) = self.rsa();
                BoxedRsaPublicKey::new(n, e)
                    .verify_pkcs1v15::<Sha256>(&msg, sig.signature)
                    .is_ok()
            }
            _ => return Err(Error::BadKey),
        };
        if ok { Ok(()) } else { Err(Error::BadSignature) }
    }
}

/// A signer re-creating BIND's signatures with the same private keys.
struct Signer {
    key: Key,
    rsa_d: Option<Vec<u8>>,
}

impl Sig0Signer for Signer {
    fn algorithm(&self) -> Algorithm {
        Algorithm::new(self.key.algorithm)
    }
    fn key_tag(&self) -> u16 {
        self.key.tag
    }
    fn signer_name(&self) -> Name<'_> {
        self.key.name.as_name()
    }
    fn signature_len(&self) -> usize {
        if self.key.algorithm == 8 { 128 } else { 64 }
    }
    fn sign(&self, data: &[&[u8]], out: &mut [u8]) -> dnsbox::Result<usize> {
        let msg = data.concat();
        let sig = match self.key.algorithm {
            15 => {
                let seed: [u8; 32] = b64(ED25519_SEED).try_into().unwrap();
                Ed25519PrivateKey::from_bytes(seed)
                    .sign(&msg)
                    .to_bytes()
                    .to_vec()
            }
            8 => {
                let (n, e) = self.key.rsa();
                let d = BoxedUint::from_be_bytes(self.rsa_d.as_ref().unwrap());
                BoxedRsaPrivateKey::from_components(n, e, d)
                    .sign_pkcs1v15::<Sha256>(&msg)
                    .unwrap()
            }
            _ => unreachable!(),
        };
        out[..sig.len()].copy_from_slice(&sig);
        Ok(sig.len())
    }
}

fn keys() -> [(&'static str, Key); 3] {
    [
        (
            "sig0-ed25519.query.bin",
            Key::new("sig0.example.com", 15, 43160, ED25519_PUB),
        ),
        (
            "sig0-p256.query.bin",
            Key::new("sig0ec.example.com", 13, 63230, P256_PUB),
        ),
        (
            "sig0-rsa.query.bin",
            Key::new("sig0rsa.example.com", 8, 34939, RSA_PUB),
        ),
    ]
}

#[test]
fn verify_bind_signatures() {
    for (file, key) in keys() {
        let wire = data(file);
        let msg = Message::parse_validated(&wire).unwrap();
        let rec = sig0::find(&msg).unwrap().expect("SIG(0)");
        assert_eq!(rec.data.algorithm.get(), key.algorithm, "{file}");
        let now = rec.data.inception + 300;
        let ok = sig0::verify(&msg, &key, now, None).unwrap();
        assert_eq!(ok, rec);
        // RFC 2931 §3.1 window, serial arithmetic.
        assert_eq!(
            sig0::verify(&msg, &key, rec.data.expiration + 1, None),
            Err(Error::BadTime)
        );
        // Any change to the signed part breaks the signature.
        for i in (0..rec.start).step_by(7) {
            let mut bad = wire.clone();
            bad[i] ^= 0x01;
            if let Ok(m) = Message::parse(&bad) {
                assert!(
                    sig0::verify(&m, &key, now, None).is_err(),
                    "{file} byte {i}"
                );
            }
        }
        // The SIG(0) is displayed like an RRSIG.
        let last = msg.additional().last().unwrap().unwrap();
        assert!(matches!(last.data().unwrap(), RData::Sig(_)));
        assert!(last.to_string().starts_with(". 0 ANY SIG TYPE0 "), "{last}");
    }
}

#[test]
fn reproduce_bind_signatures() {
    let [(ed_file, ed_key), _, (rsa_file, rsa_key)] = keys();
    for (file, signer) in [
        (
            ed_file,
            Signer {
                key: ed_key,
                rsa_d: None,
            },
        ),
        (
            rsa_file,
            Signer {
                key: rsa_key,
                rsa_d: Some(b64(RSA_D)),
            },
        ),
    ] {
        let wire = data(file);
        let msg = Message::parse(&wire).unwrap();
        let rec = sig0::find(&msg).unwrap().unwrap();
        // Rebuild the update without its SIG(0) and sign it again.
        let mut buf = [0u8; 1024];
        let mut b = MessageBuilder::new(&mut buf).unwrap();
        b.set_id(msg.id());
        b.set_flags(msg.flags());
        for q in msg.questions() {
            b.copy_question(&q.unwrap()).unwrap();
        }
        for item in msg.records() {
            let (section, rr) = item.unwrap();
            if rr.start() == rec.start {
                break;
            }
            b.copy_record(section, &rr).unwrap();
        }
        assert_eq!(&b.as_bytes()[12..], &wire[12..rec.start]);
        let validity = Validity {
            inception: rec.data.inception,
            expiration: rec.data.expiration,
        };
        sig0::sign(&mut b, &signer, validity, None).unwrap();
        assert_eq!(b.finish(), &wire[..], "{file}");
    }
}

#[test]
fn signed_data_matches_rfc_layout() {
    let wire = data("sig0-ed25519.query.bin");
    let msg = Message::parse(&wire).unwrap();
    let rec = sig0::find(&msg).unwrap().unwrap();
    let sd = SignedData::new(&rec.data, &wire, Some(rec.start), None).unwrap();
    let [fields, request, header, body] = sd.parts();
    assert_eq!(fields.len(), 18 + 18); // fixed part + "sig0.example.com."
    assert!(request.is_empty());
    assert_eq!(&header[..10], &wire[..10]);
    assert_eq!(&header[10..], &[0, 0]); // ARCOUNT without the SIG(0)
    assert_eq!(body, &wire[12..rec.start]);
}

/// The library's own DNSSEC backend verifies BIND's SIG(0) signatures
/// through the SIG(0) adapters, and re-signs the Ed25519 update byte for
/// byte.
#[cfg(feature = "dnssec")]
#[test]
fn dnssec_backend_adapters() {
    use dnsbox::dnssec::{PurecryptoVerifier, SigningKey};
    use dnsbox::rdata::Key as KeyRdata;
    use dnsbox::sig0::{DnssecSig0Signer, DnssecSig0Verifier};

    for (file, key) in keys() {
        let wire = data(file);
        let msg = Message::parse_validated(&wire).unwrap();
        let rec = sig0::find(&msg).unwrap().unwrap();
        // `dnssec-keygen -T KEY -n HOST` keys: flags 512, protocol 3.
        let rdata = KeyRdata::new(512, 3, Algorithm::new(key.algorithm), &key.public);
        assert_eq!(rdata.key_tag(), key.tag, "{file}");
        let v = DnssecSig0Verifier::new(PurecryptoVerifier, key.name.as_name(), rdata);
        let now = rec.data.inception + 300;
        assert_eq!(sig0::verify(&msg, &v, now, None), Ok(rec), "{file}");
        let mut bad = wire.clone();
        bad[rec.start - 1] ^= 1;
        let m = Message::parse(&bad).unwrap();
        assert!(sig0::verify(&m, &v, now, None).is_err(), "{file}");
        // A different KEY: BADKEY.
        let other = KeyRdata::new(512, 3, Algorithm::new(key.algorithm), &[1; 32]);
        let v = DnssecSig0Verifier::new(PurecryptoVerifier, key.name.as_name(), other);
        assert_eq!(sig0::verify(&msg, &v, now, None), Err(Error::BadKey));
    }

    // Ed25519 is deterministic: re-signing reproduces BIND's message.
    let [(file, key), ..] = keys();
    let wire = data(file);
    let msg = Message::parse(&wire).unwrap();
    let rec = sig0::find(&msg).unwrap().unwrap();
    let sk = SigningKey::from_private_bytes(Algorithm::ED25519, &b64(ED25519_SEED)).unwrap();
    let signer = DnssecSig0Signer::new(&sk, key.name.as_name(), 512);
    assert_eq!(signer.key().public_key, &key.public[..]);
    let mut buf = [0u8; 1024];
    let mut b = MessageBuilder::new(&mut buf).unwrap();
    b.set_id(msg.id());
    b.set_flags(msg.flags());
    for q in msg.questions() {
        b.copy_question(&q.unwrap()).unwrap();
    }
    for item in msg.records() {
        let (section, rr) = item.unwrap();
        if rr.start() == rec.start {
            break;
        }
        b.copy_record(section, &rr).unwrap();
    }
    let validity = Validity {
        inception: rec.data.inception,
        expiration: rec.data.expiration,
    };
    sig0::sign(&mut b, &signer, validity, None).unwrap();
    assert_eq!(b.finish(), &wire[..]);
}
